name: Tarefa
description: Template para tarefas
title: "[Tarefa] "
labels:
  - tipo:feature
body:
  - type: textarea
    id: o-que
    attributes:
      label: O que
      description: Breve descrição da tarefa.
      placeholder: Explique claramente o objetivo.
    validations:
      required: true

  - type: textarea
    id: como-validar
    attributes:
      label: Como validar
      description: Passos simples para testar.
      placeholder: 1) ... 2) ... 3) ...
    validations:
      required: true

  - type: checkboxes
    id: definicao-de-pronto
    attributes:
      label: Definição de pronto
      options:
        - label: Critério 1
        - label: Critério 2

  - type: input
    id: estimativa
    attributes:
      label: Estimativa
      placeholder: "Ex.: 4h ou 2 dias"
    validations:
      required: false

  - type: dropdown
    id: area
    attributes:
      label: Área
      options:
        - auth
        - jogadores
        - treinos
        - docs
        - app
        - relatorios
    validations:
      required: true

  - type: dropdown
    id: rotulos
    attributes:
      label: Rótulos
      multiple: true
      options:
        - prioridade:alta
        - prioridade:média
        - tipo:feature
        - tipo:infra
        - tipo:ux
        - tipo:bug

  - type: input
    id: responsavel
    attributes:
      label: Responsável
      placeholder: "@login"
      description: Informe o usuário a ser atribuído (atribua também na barra lateral após abrir o issue).
